val schema_1766585976 = new StructType()
  .add("patient_id", "string")
  .add("date_of_birth", "string")
  .add("address_us_state", "string")
  .add("address_us_zip", "string")
  .add("npi", "string")
  .add("date_of_service", "string")
  .add("lab_result", "string")
  .add("specimen_type", "string")