val schema_1778781734 = new StructType()
  .add("patient_id", "string")
  .add("date_of_birth", "string")
  .add("address_us_state", "string")
  .add("address_us_zip", "string")
  .add("icd_code_1", "string")
  .add("icd_code_2", "string")
  .add("date_of_service", "string")
  .add("admission_date", "string")
  .add("discharge_date", "string")
  .add("claim_type", "string")
  .add("amount_billed", "string")
  .add("amount_paid", "string")