// Databricks notebook source
// MAGIC %md Notebook: stage/common_v2

// COMMAND ----------

spark.conf.set("spark.sql.legacy.parquet.datetimeRebaseModeInRead", "CORRECTED")
spark.conf.set("spark.sql.legacy.parquet.datetimeRebaseModeInWrite", "CORRECTED")
spark.conf.set("spark.sql.legacy.timeParserPolicy", "CORRECTED")
spark.conf.set("spark.sql.csv.parser.columnPruning.enabled", false)

// COMMAND ----------

import org.apache.spark.sql._
import org.apache.spark.sql.functions._
import org.apache.spark.sql.types._

import java.util.Base64
import java.util.zip._
import java.nio.charset.StandardCharsets
import java.io.{ByteArrayOutputStream, ByteArrayInputStream}

// import com.google.api.client.util.DateTime;
import java.time.Instant
import java.time.ZoneId
import java.sql.Timestamp

import scala.concurrent.Future

// import ai.prognos.DataQuality.util.database._

// import ai.prognos.admissions_client._
import sys.process._

// COMMAND ----------

// ai.prognos.admissions_client.Config.setEnvironment("production")
// ai.prognos.admissions_client.Config.setAPIKey(dbutils.secrets.get(scope = "admissions-client", key = "production-api-key"))

// COMMAND ----------

// MAGIC %md ### Import Redaction Library

// COMMAND ----------

// MAGIC %run "./redactor/lab-redactor-production-11-18-24"

// COMMAND ----------

// MAGIC %md ### Payload Processing

// COMMAND ----------

def compress(p: String): String = {  
  val inData = p.getBytes()

  val deflater = new Deflater()
  deflater.setInput(inData)
  deflater.finish()

  val compressedData = new Array[Byte](inData.size * 2)

  var count = deflater.deflate(compressedData)
  deflater.end()

  val compressedBytes = compressedData.take(count)

  return new String(Base64.getEncoder().encode(compressedBytes))
}

// COMMAND ----------

def decompress(inData: Array[Byte]): Array[Byte] = {
  val inflater = new Inflater()
  inflater.setInput(inData)
  val decompressedData = new Array[Byte](inData.size * 2)
  var count = inflater.inflate(decompressedData)
  var finalData = decompressedData.take(count)
  while (count > 0) {
    count = inflater.inflate(decompressedData)
    finalData = finalData ++ decompressedData.take(count)
  }
  
  return finalData 
 }

// COMMAND ----------

def decompressPayload(p: String): String = {
  val decodedPayload = Base64.getDecoder().decode(p)
  new String(decompress(decodedPayload), StandardCharsets.UTF_8)
}

// COMMAND ----------

def extractPayload(p: String): DataFrame = {
  spark.read.option("multiline","true").json(Seq(p).toDS)
}

// COMMAND ----------

def extractPayloadCompressed(p: String): DataFrame = {
  extractPayload(decompressPayload(p))
}

// COMMAND ----------

// MAGIC %md ### Functions

// COMMAND ----------

def withParquetCompatibleColumnNames()(df: DataFrame): DataFrame = {    
    df.columns.foldLeft(df) { (tmpDF, col) =>
      val newName = col.replaceAll("[,;{}()\n\t=]", "").replaceAll(" ", "_").toLowerCase()
      tmpDF.withColumnRenamed(col, newName)
    }
}

// COMMAND ----------

def withMetaRecordHash()(df: DataFrame): DataFrame = {
  val cols = df.columns.map(c => {
    when(col(c).isNull, "").otherwise(col(c))
  })
    
  df.withColumn("meta_record_hash", md5(concat_ws("|", cols: _*)))
}

// COMMAND ----------

def withPayloadAttributes(r: Row)(df: DataFrame): DataFrame = {
  println("====================== withPayloadAttributes ======================")
  
  val registrationId = lit(r.getAs[String]("registration-id"))
  val datanatorId = lit(r.getAs[Long]("datanator-id"))
  val partner = lit(r.getAs[String]("partner"))

  println(s"registrationId: ${registrationId}")
  println(s"datanatorId: ${datanatorId}")
  println(s"partner: ${partner}")

  println("------------ resultDF ----------------")

  val resultDF = Registrar.getRecordByID(registrationId.toString)
    
  resultDF.show(false)

  val registrationTimestampAsString = resultDF.head().getAs[String]("created-at")

  val gdt = DateTime.parseRfc3339(registrationTimestampAsString);
  val jdt = Instant.ofEpochMilli(gdt.getValue()).atZone(ZoneId.of("UTC")).toLocalDateTime()

  val registrationTimestamp = java.sql.Timestamp.valueOf(jdt)
  val attributes = resultDF.head().getAs[String]("attributes")
  
  println("------------ new attributes ----------------")
  println(s"registrationTimestamp: ${registrationTimestamp}")
  println(s"attributes: ${attributes}")
  
  println("====================== END withPayloadAttributes ======================")
  
  df.withColumn("meta_registration_id", registrationId)
    .withColumn("meta_datanator_id", datanatorId)
    .withColumn("meta_partner", partner)
    .withColumn("meta_registration_timestamp", lit(registrationTimestamp))
    .withColumn("meta_staged_timestamp", current_timestamp())
    .withColumn("meta_attributes", lit(attributes).cast(StringType))
}

// COMMAND ----------

def loadCsv(reader: DataFrameReader, r: Row): DataFrame = {
  val path = r.getAs[String]("in")
  println(path)
  
  reader
    .csv(path)
    .transform(withParquetCompatibleColumnNames())
    .transform(withMetaRecordHash())
    .transform(withPayloadAttributes(r))
}

// COMMAND ----------

def unionCsvPayload(reader: DataFrameReader, payloadDF: DataFrame): DataFrame = {
  val dfs = payloadDF.collect().foldLeft(List[DataFrame]())((l, r) => {
    println(l)
    println(r)

    loadCsv(reader, r) :: l
  })
  
  dfs.reduce(_.union(_))
}

// COMMAND ----------

def loadParquet(r: Row): DataFrame = {
  val path = r.getAs[String]("in")
  println(path)
  
  val df = spark
    .read
    .parquet(path)
    .transform(withMetaRecordHash())
    .transform(withPayloadAttributes(r))
  
  val sortedCols = df.columns.sorted.map(str => col(str))
  
  df.select(sortedCols:_*)
}

// COMMAND ----------

def writeStandardParquetOutput(df: DataFrame, outputPath: String): Unit = {
  df.repartition(col("meta_registration_id"))
    .write
    .mode(SaveMode.Append)
    .partitionBy("meta_registration_id")
    .parquet(outputPath)
}

// COMMAND ----------

class ParquetPayloadDumper(val t: (DataFrame) => DataFrame = (df: DataFrame) => { df }) {

  val rand = scala.util.Random
  var hadError = false
  
  def dumpThreaded(r: Row, outputPath: String): Thread = {
    new Thread {
      override def run {
        try {
          val pool = rand.nextInt(20)
          spark.sparkContext.setLocalProperty("spark.scheduler.pool", s"pool_${pool}")

          println("thread run")
          println(r)
          
          val outDF = loadParquet(r).transform(t)
          
          outDF.printSchema
          
          //outDF.coalesce(1).write.mode(SaveMode.Append).parquet(outputPath)
          writeStandardParquetOutput(outDF, outputPath)
        }
        catch {
          case e: Exception => { e.printStackTrace ; hadError = true }
        }
      }
    }
  }
  
}

// COMMAND ----------

def writeParquetPayload(payloadDF: DataFrame, outputPath: String, t: (DataFrame) => DataFrame = (df: DataFrame) => { df }): Unit = {
  
  val dumper = new ParquetPayloadDumper(t)
  
  val threads = payloadDF.collect().map((r: Row) => {
    dumper.dumpThreaded(r, outputPath)
  })
  
  for(t <- threads) { t.start }
  for(t <- threads) { t.join }
  
  if (dumper.hadError) {
    throw new Exception("failed running one of the dump threads please see error log for details")
  }
}

// COMMAND ----------

case class ZipProcessor( 
    delimiter: String,
    hasHeader: Boolean,
    schema: StructType,
    datanatorId: Int,
    outputUnzipBucket: String // write out unzipped file to intermediary s3 location (auto-deletes based on bucket policy)
) {

  val reader =
    spark.read
      .option("header", hasHeader.toString)
      .option("charset", "UTF8")
      .option("delimiter", delimiter)
      .option("mode", "DROPMALFORMED")
      .option("ignoreTrailingWhiteSpace", "true")
      .option("ignoreLeadingWhiteSpace", "true")
      .schema(schema)

  def processPayloadRow(row: Row, payloadDF: DataFrame): DataFrame = {
    val s3InputPath = row.getAs[String]("in")
    val registrationId = row.getAs[String]("registration-id")

    val payloadDfCurrent = payloadDF.filter(col("registration-id") === registrationId)
    
    if (s3InputPath.contains(".zip")) {
      val dbfsInputPath = s"/notch/zipped/$registrationId.zip"
      val dbfsUnzipPath = s"/notch/unzipped/$registrationId/"
      val s3OutputPath = s"s3://$outputUnzipBucket/unzip/$datanatorId/$registrationId"

      println(s"Processing ZIP for: $registrationId")

      dbutils.fs.cp(s3InputPath, s"file:/dbfs$dbfsInputPath")
      println("Copied zip file from s3 to dbfs")
  
      dbutils.fs.mkdirs(s"file:/dbfs$dbfsUnzipPath")

      println("Unzipping file in dbfs")
      val unzipCmd = s"unzip /dbfs$dbfsInputPath -d /dbfs$dbfsUnzipPath"
      val result = unzipCmd.!
      println(result)

      dbutils.fs.cp(s"file:/dbfs$dbfsUnzipPath", s3OutputPath, recurse = true)
      println("Copied unzipped file(s) from dbfs to S3")
      dbutils.fs.rm(s"file:/dbfs$dbfsInputPath")
      println("Removed zipped file from dbfs")
      dbutils.fs.rm(s"file:/dbfs$dbfsUnzipPath", recurse = true)
      println("Removed unzipped file from dbfs")

      unionCsvPayload(reader, payloadDfCurrent.withColumn("in", lit(s3OutputPath)))

    } else {
      println(s"Processing non-ZIP for: $registrationId") 

      unionCsvPayload(reader, payloadDfCurrent)
    }
  }
}

// COMMAND ----------

// MAGIC %md ### Schemas

val schema_1778837868 = new StructType()
  .add("patient_id", "string")
  .add("date_of_birth", "string")
  .add("address_us_state", "string")
  .add("address_us_zip", "string")
  .add("icd_code_1", "string")
  .add("icd_code_2", "string")
  .add("date_of_service", "string")
  .add("admission_date", "string")
  .add("discharge_date", "string")
  .add("claim_type", "string")
  .add("amount_billed", "string")
  .add("amount_paid", "string")


// COMMAND ----------

val schema_10100 = new StructType()
  .add("Record ID", "string")
  .add("Date Authorized", "string")
  .add("Time Authorized", "string")
  .add("BIN Number", "string")
  .add("Version Number", "string")
  .add("Transaction Code", "string")
  .add("Processor Control Number", "string")
  .add("Transaction Count", "string")
  .add("Service Provider ID", "string")
  .add("Service Provider ID Qualifier", "string")
  .add("Date Of Service", "string")
  .add("Patient Date Of Birth", "string")
  .add("Patient Gender Code", "string")
  .add("Patient Location", "string")
  .add("Patient First Name", "string")
  .add("Patient Last Name", "string")
  .add("Patient Street Address", "string")
  .add("Patient State/Province", "string")
  .add("Patient Zip/Postal Zone", "string")
  .add("Patient ID Qualifier", "string")
  .add("Patient ID", "string")
  .add("Provider ID", "string")
  .add("Provider ID Qualifier", "string")
  .add("Prescriber ID", "string")
  .add("Primary Care Provider ID", "string")
  .add("Prescriber Last Name", "string")
  .add("Prescriber ID Qualifier", "string")
  .add("Primary Care Provider ID Qualifier", "string")
  .add("Group ID", "string")
  .add("Cardholder ID", "string")
  .add("Person Code", "string")
  .add("Patient Relationship Code", "string")
  .add("Eligibility Clarification Code", "string")
  .add("Home Plan", "string")
  .add("Coordination of Benefits Count", "string")
  .add("Other Payer Coverage Type", "string")
  .add("Other Payer ID Qualifier", "string")
  .add("Other Payer ID", "string")
  .add("Other Payer Amount Paid Qualifier", "string")
  .add("Other Payer Amount Paid Submitted", "string")
  .add("Other Payer Date", "string")
  .add("Carrier ID", "string")
  .add("Date Of Injury", "string")
  .add("Claim/Reference ID", "string")
  .add("Other Coverage Code", "string")
  .add("Prescription/Service Reference Number", "string")
  .add("Fill Number", "string")
  .add("Days Supply", "string")
  .add("Compound Code", "string")
  .add("Product/Service ID", "string")
  .add("Dispense As Written (DAW)/Product Select Code", "string")
  .add("Date Prescription Written", "string")
  .add("Number Of Refills Authorized", "string")
  .add("Level Of Service", "string")
  .add("Prescription Origin Code", "string")
  .add("Submission Clarification Code", "string")
  .add("Unit Dose Indicator", "string")
  .add("Product/Service ID Qualifier", "string")
  .add("Quantity Dispensed", "string")
  .add("Orig Prescribed Product/Service Code", "string")
  .add("Orig Prescribed Quantity", "string")
  .add("Orig Prescribed Product/Service Code Qualifier", "string")
  .add("Prescription/Service Reference Number Qualifier", "string")
  .add("Prior Authorization Type Code", "string")
  .add("Unit Of Measure", "string")
  .add("Reason For Service", "string")
  .add("Professional Service Code", "string")
  .add("Result Of Service Code", "string")
  .add("Coupon Type", "string")
  .add("Coupon Number", "string")
  .add("Coupon Value Amount", "string")
  .add("Ingredient Cost Submitted", "string")
  .add("Dispensing Fee Submitted", "string")
  .add("Basis of Cost Determination", "string")
  .add("Usual And Customary Charge", "string")
  .add("Patient Paid Amount Submitted", "string")
  .add("Gross Amount Due Submitted", "string")
  .add("Incentive Amount Submitted", "string")
  .add("Professional Service Fee Submitted", "string")
  .add("Other Amount Claimed Submitted Qualifier", "string")
  .add("Other Amount Claimed Submitted", "string")
  .add("Flat Sales Tax Amount Submitted", "string")
  .add("Percent Sales Tax Amount Submitted", "string")
  .add("Percent Sales Tax Rate Submitted", "string")
  .add("Percent Sales Tax Basis Submitted", "string")
  .add("Diagnosis Code", "string")
  .add("Diagnosis Code Qualifier", "string")
  .add("Response Code", "string")
  .add("Patient Pay Amount", "string")
  .add("Ingredient Cost Paid", "string")
  .add("Dispensing Fee Paid", "string")
  .add("Total Amount Paid", "string")
  .add("Accumulated Deductible Amount", "string")
  .add("Remaining Deductible Amount", "string")
  .add("Remaining Benefit Amount", "string")
  .add("Amount Applied to Periodic Deductible", "string")
  .add("Amount Of Copay/Coinsurance", "string")
  .add("Amount Attributed To Product Selection", "string")
  .add("Amount Exceeding Periodic Benefit Maximum", "string")
  .add("Incentive Amount Paid", "string")
  .add("Basis of Reimbursement Determination", "string")
  .add("Amount Attributed to Sales Tax", "string")
  .add("Tax Exempt Indicator", "string")
  .add("Flat Sales Tax Amount Paid", "string")
  .add("Percentage Sales Tax Amount Paid", "string")
  .add("Percent Sales Tax Rate Paid", "string")
  .add("Percent Sales Tax Basis Paid", "string")
  .add("Professional Service Fee Paid", "string")
  .add("Other Amount Paid Qualifier", "string")
  .add("Other Amount Paid", "string")
  .add("Other Payer Amount Recognized", "string")
  .add("Plan Identification", "string")
  .add("NCPDP Number", "string")
  .add("National Provider ID", "string")
  .add("Plan Type", "string")
  .add("Pharmacy Location (Postal Code)", "string")
  .add("Reject Code 1", "string")
  .add("Reject Code 2", "string")
  .add("Reject Code 3", "string")
  .add("Reject Code 4", "string")
  .add("Reject Code 5", "string")
  .add("Payer ID", "string")
  .add("Payer ID Qualifier", "string")
  .add("Plan Name", "string")
  .add("Type of Payment", "string")
  .add("Change Healthcare Claim ID", "string")
  .add("Filler", "string")

// COMMAND ----------

val schema_10200_S = new StructType()
  .add("Change Healthcare Claim ID", "string")
  .add("RECORD_TYPE", "string")
  .add("SERVICE_LINE_NUMBER", "string")
  .add("SERVICE_FROM_DATE", "string")
  .add("SERVICE_TO_DATE", "string")
  .add("PLACE_OF_SERVICE", "string")
  .add("PROCEDURE_CODE", "string")
  .add("PROCEDURE_CODE_QUAL", "string")
  .add("PROCEDURE_MODIFIER_1", "string")
  .add("PROCEDURE_MODIFIER_2", "string")
  .add("PROCEDURE_MODIFIER_3", "string")
  .add("PROCEDURE_MODIFIER_4", "string")
  .add("SERVICE_LINE_CHARGE_AMOUNT", "string")
  .add("DROP 01", "string")
  .add("UNIT_COUNT", "string")
  .add("REVENUE_CODE", "string")
  .add("DIAGNOSIS_CODE_POINTER_1", "string")
  .add("DIAGNOSIS_CODE_POINTER_2", "string")
  .add("DIAGNOSIS_CODE_POINTER_3", "string")
  .add("DIAGNOSIS_CODE_POINTER_4", "string")
  .add("DROP 02", "string")
  .add("DROP 03", "string")
  .add("DROP 04", "string")
  .add("DROP 05", "string")
  .add("NATIONAL_DRUG_CODE", "string")
  .add("DROP 06", "string")
  .add("EMERGENCY_INDICATOR", "string")
  .add("DROP 07", "string")
  .add("DROP 08", "string")
  .add("DROP 09", "string")
  .add("DROP 10", "string")
  .add("DROP 11", "string")
  .add("DROP 12", "string")
  .add("DROP 13", "string")
  .add("DROP 14", "string")
  .add("DROP 15", "string")
  .add("DROP 16", "string")
  .add("DROP 17", "string")
  .add("DROP 18", "string")
  .add("DROP 19", "string")
  .add("DROP 20", "string")
  .add("DROP 21", "string")


// COMMAND ----------

val schema_10200_C = new StructType()
  .add("Change Healthcare Claim ID", "string")
  .add("RECORD_TYPE", "string")
  .add("PAYER_ID", "string")
  .add("CODING_TYPE", "string")
  .add("RECEIVED_DATE", "string")
  .add("CLAIM_TYPE", "string")
  .add("DROP 01", "string")
  .add("PAYER_NAME", "string")
  .add("SUBMITTER_ID", "string")
  .add("DROP 02", "string")
  .add("DROP 03", "string")
  .add("DROP 04", "string")
  .add("DROP 05", "string")
  .add("DROP 06", "string")
  .add("MEMBER_BIRTH_YEAR", "string")
  .add("DROP 07", "string")
  .add("DROP 08", "string")
  .add("DROP 09", "string")
  .add("PATIENT_STATE", "string")
  .add("PATIENT_ZIP3", "string")
  .add("DROP 10", "string")
  .add("PATIENT_RELATIONSHIP_CODE", "string")
  .add("DROP 11", "string")
  .add("DROP 12", "string")
  .add("PATIENT_GENDER_CODE", "string")
  .add("PATIENT_BIRTH_YEAR", "string")
  .add("DROP 13", "string")
  .add("BILLING_PROV_ID", "string")
  .add("BILLING_PROV_NPI", "string")
  .add("BILLING_PROV_ORG_NAME", "string")
  .add("BILLING_PROV_IND_NAME", "string")
  .add("BILLING_PROV_STREET_ADDRESS_1", "string")
  .add("BILLING_PROV_STREET_ADDRESS_2", "string")
  .add("BILLING_PROV_CITY", "string")
  .add("BILLING_PROV_STATE", "string")
  .add("BILLING_PROV_ZIP", "string")
  .add("DROP 14", "string")
  .add("REFERRING_PROV_NPI", "string")
  .add("DROP 15", "string")
  .add("REFERRING_PROV_NAME", "string")
  .add("DROP 16", "string")
  .add("RENDERING/ATTENDING_PROV_NPI", "string")
  .add("RENDERING_PROV_ORG_NAME", "string")
  .add("RENDERING/ATTENDING_PROV_IND_NAME", "string")
  .add("DROP 17", "string")
  .add("FACILITY_NAME", "string")
  .add("DROP 18", "string")
  .add("FACILITY_STREET_ADDRESS_1", "string")
  .add("FACILITY_STREET_ADDRESS_2", "string")
  .add("FACILITY_CITY", "string")
  .add("FACILITY_STATE", "string")
  .add("FACILITY_ZIP", "string")
  .add("STATEMENT_FROM_DATE", "string")
  .add("STATEMENT_TO_DATE", "string")
  .add("TOTAL_CLAIM_CHARGE_AMT", "string")
  .add("DROP 19", "string")
  .add("DRG_CODE", "string")
  .add("DROP 20", "string")
  .add("BILL_TYPE", "string")
  .add("PATIENT_SIGNATURE_SOURCE_CD", "string")
  .add("BEBEFITS_ASSIGNMENT_CERT_IND", "string")
  .add("DROP 21", "string")
  .add("PRINCIPAL_INST_PROCEDURE_CODE", "string")
  .add("ADMITTING_DIAGNOSIS_CODE", "string")
  .add("PRINCIPAL_DIAGNOSIS_CODE", "string")
  .add("OTHER_DIAGNOSIS_CODE_1", "string")
  .add("OTHER_DIAGNOSIS_CODE_2", "string")
  .add("OTHER_DIAGNOSIS_CODE_3", "string")
  .add("OTHER_DIAGNOSIS_CODE_4", "string")
  .add("OTHER_DIAGNOSIS_CODE_5", "string")
  .add("OTHER_DIAGNOSIS_CODE_6", "string")
  .add("OTHER_DIAGNOSIS_CODE_7", "string")
  .add("OTHER_INST_PROC_CODE_1", "string")
  .add("OTHER_INST_PROC_CODE_2", "string")
  .add("OTHER_INST_PROC_CODE_3", "string")
  .add("OTHER_INST_PROC_CODE_4", "string")
  .add("OTHER_INST_PROC_CODE_5", "string")
  .add("DROP 22", "string")
  .add("CLAIM_FILING_INDICATOR_CD", "string")
  .add("DROP 23", "string")
  .add("ACCIDENT_RELATED_IND", "string")
  .add("DROP 24", "string")
  .add("DROP 25", "string")
  .add("DROP 26", "string")
  .add("DROP 27", "string")
  .add("DROP 28", "string")
  .add("DROP 29", "string")
  .add("DROP 30", "string")
  .add("DROP 31", "string")
  .add("DROP 32", "string")
  .add("DROP 33", "string")
  .add("ADMISSION_DATE", "string")
  .add("DROP 34", "string")
  .add("ADMISSION_TYPE_CODE", "string")
  .add("ADMISSION_SOURCE_CODE", "string")
  .add("DROP 35", "string")
  .add("PATIENT_STATUS_CODE", "string")
  .add("DROP 36", "string")
  .add("OTHER_INST_PROC_CODE_6", "string")
  .add("OTHER_INST_PROC_CODE_7", "string")
  .add("OTHER_INST_PROC_CODE_8", "string")
  .add("OTHER_INST_PROC_CODE_9", "string")
  .add("BILLING_PR_TAXONOMY", "string")
  .add("BILLING_PR_STATE_LICENSE", "string")
  .add("DROP 37", "string")
  .add("BILLING_PR_SSN", "string")
  .add("RENDERING/ATTENDING_PROV_TAXONOMY", "string")
  .add("RENDERING/ATTENDING_PROV_STATE_LICENSE", "string")
  .add("DROP 38", "string")
  .add("FACILITY_NPI", "string")
  .add("FACILITY_STATE_LICENSE", "string")

// COMMAND ----------

val schema_10200_D = new StructType()
  .add("Change Healthcare Claim ID", "string")
  .add("RECORD_TYPE", "string")
  .add("OTHER_DIAGNOSIS_CODE_8", "string")
  .add("OTHER_DIAGNOSIS_CODE_9", "string")
  .add("OTHER_DIAGNOSIS_CODE_10", "string")
  .add("OTHER_DIAGNOSIS_CODE_11", "string")
  .add("OTHER_DIAGNOSIS_CODE_12", "string")
  .add("OTHER_DIAGNOSIS_CODE_13", "string")
  .add("OTHER_DIAGNOSIS_CODE_14", "string")
  .add("OTHER_DIAGNOSIS_CODE_15", "string")
  .add("OTHER_DIAGNOSIS_CODE_16", "string")
  .add("OTHER_DIAGNOSIS_CODE_17", "string")
  .add("OTHER_DIAGNOSIS_CODE_18", "string")
  .add("OTHER_DIAGNOSIS_CODE_19", "string")
  .add("OTHER_DIAGNOSIS_CODE_20", "string")
  .add("OTHER_DIAGNOSIS_CODE_21", "string")
  .add("OTHER_DIAGNOSIS_CODE_22", "string")
  .add("OTHER_DIAGNOSIS_CODE_23", "string")
  .add("OTHER_DIAGNOSIS_CODE_24", "string")
  .add("OTHER_INST_PROC_CODE_10", "string")
  .add("OTHER_INST_PROC_CODE_11", "string")
  .add("OTHER_INST_PROC_CODE_12", "string")
  .add("OTHER_INST_PROC_CODE_13", "string")
  .add("OTHER_INST_PROC_CODE_14", "string")
  .add("OTHER_INST_PROC_CODE_15", "string")
  .add("OTHER_INST_PROC_CODE_16", "string")
  .add("OTHER_INST_PROC_CODE_17", "string")
  .add("OTHER_INST_PROC_CODE_18", "string")
  .add("OTHER_INST_PROC_CODE_19", "string")
  .add("OTHER_INST_PROC_CODE_20", "string")
  .add("OTHER_INST_PROC_CODE_21", "string")
  .add("OTHER_INST_PROC_CODE_22", "string")
  .add("OTHER_INST_PROC_CODE_23", "string")
  .add("OTHER_INST_PROC_CODE_24", "string")
  .add("CLAIM_FILING_IND_CD", "string")
  .add("REFERRING_PROV_STATE_LICENSE", "string")
  .add("DROP 01", "string")
  .add("REFERRING_PROV_COMMERCIAL_ID", "string")
  .add("PAY_TO_PROV_ADDRESS_1", "string")
  .add("PAY_TO_PROV_ADDRESS_2", "string")
  .add("PAY_TO_PROV_CITY", "string")
  .add("PAY_TO_PROV_ZIP", "string")
  .add("PAY_TO_PROV_STATE", "string")
  .add("DROP 02", "string")
  .add("SUPERVISING_PROV_LAST_NAME", "string")
  .add("SUPERVISING_PROV_FIRST_NAME", "string")
  .add("SUPERVISING_PROV_MIDDLE_NAME", "string")
  .add("SUPERVISING_PROV_NPI", "string")
  .add("SUPERVISING_PROV_STATE_LICENSE", "string")
  .add("DROP 03", "string")
  .add("SUPERVISING_PROV_COMMERCIAL_ID", "string")
  .add("SUPERVISING_PROV_LOCATION", "string")
  .add("DROP 04", "string")
  .add("OPERATING_PROV_LAST_NAME", "string")
  .add("OPERATING_PROV_FIRST_NAME", "string")
  .add("OPERATING_PROV_MIDDLE_NAME", "string")
  .add("OPERATING_PROV_NPI", "string")
  .add("OPERATING_PROV_STATE_LICENSE", "string")
  .add("DROP 05", "string")
  .add("OPERATING_PROV_COMMERCIAL", "string")
  .add("OPERATING_PROV_LOCATION", "string")
  .add("DROP 06", "string")
  .add("OTH_OPERATING_PROV_LAST_NAME", "string")
  .add("OTH_OPERATING_PROV_FIRST_NAME", "string")
  .add("OTH_OPERATING_PROV_MIDDLE_NAME", "string")
  .add("OTH_OPERATING_PROV_NPI", "string")
  .add("OTH_OPERATING_PROV_STATE_LICENSE", "string")
  .add("DROP 07", "string")
  .add("OTH_OPERATING_PROV_COMMERCIAL_ID", "string")
  .add("OTH_OPERATING_PROV_LOCATION", "string")
  .add("PAY_TO_PLAN_NAME", "string")
  .add("PAY_TO_PLAN_ADDRESS_1", "string")
  .add("PAY_TO_PLAN_ADDRESS_2", "string")
  .add("PAY_TO_PLAN_CITY", "string")
  .add("PAY_TO_PLAN_ZIP", "string")
  .add("PAY_TO_PLAN_STATE", "string")
  .add("PAY_TO_PLAN_NAIC_CODE", "string")
  .add("PAY_TO_PLAN_PAYER_ID", "string")
  .add("PAY_TO_PLAN_PLAN_ID", "string")
  .add("PAY_TO_PLAN_CLM_OFC_NUMBER", "string")
  .add("PAY_TO_PLAN_TAX_ID", "string")
  .add("COB1_PAYER_NAME", "string")
  .add("COB1_PAYER_ID", "string")
  .add("COB1_HPID", "string")
  .add("COB1_RESP_SEQ_CD", "string")
  .add("DROP 08", "string")
  .add("DROP 09", "string")
  .add("DROP 10", "string")
  .add("COB1_INS_TYPE_CD", "string")
  .add("COB1_CLM_FILING_IND_CD", "string")
  .add("COB2_PAYER_NAME", "string")
  .add("COB2_PAYER_ID", "string")
  .add("COB2_HPID", "string")
  .add("COB2_RESP_SEQ_CD", "string")
  .add("DROP 11", "string")
  .add("DROP 12", "string")
  .add("DROP 13", "string")
  .add("COB2_INS_TYPE_CD", "string")
  .add("COB2_CLM_FILING_IND_CD", "string")
  .add("COB3_PAYER_NAME", "string")
  .add("COB3_PAYER_ID", "string")
  .add("COB3_HPID", "string")
  .add("COB3_RESP_SEQ_CD", "string")
  .add("DROP 14", "string")
  .add("DROP 15", "string")
  .add("DROP 16", "string")
  .add("COB3_INS_TYPE_CD", "string")
  .add("COB3_CLM_FILING_IND_CD", "string")
  .add("COB4_PAYER_NAME", "string")
  .add("COB4_PAYER_ID", "string")
  .add("COB4_HPID", "string")

// COMMAND ----------

val schema_21001 = new StructType()
  .add("PATIENT_ID", "string")
  .add("GENDER_CDE", "string")
  .add("LAST_NME", "string")
  .add("FIRST_NME", "string")
  .add("ADDR_LINE_1_TXT", "string")
  .add("ADDR_LINE_2_TXT", "string")
  .add("ZIP_5_POSTAL_CDE", "string")
  .add("BIRTH_DTE", "string")
  .add("SSN", "string")
  .add("effective_date", "string")
  .add("end_date", "string")
  .add("lob", "string")
  .add("update_tms", "string")
  .add("Token_1", "string")
  .add("Token_2", "string")
  .add("Token_3", "string")
  .add("Token_4", "string")
  .add("Token_5", "string")
  .add("Token_7", "string")
  .add("TokenEncryptionKey", "string")

// COMMAND ----------

val schema_1708537431 = new StructType()
  .add("PATIENT_ID", "string")
  .add("GENDER_CDE", "string")
  .add("LAST_NME", "string")
  .add("FIRST_NME", "string")
  .add("ADDR_LINE_1_TXT", "string")
  .add("ADDR_LINE_2_TXT", "string")
  .add("ZIP_5_POSTAL_CDE", "string")
  .add("BIRTH_DTE", "string")
  .add("SSN", "string")
  .add("effective_date", "string")
  .add("end_date", "string")
  .add("lob", "string")
  .add("update_tms", "string")
  .add("mx_eligible", "string")
  .add("rx_eligible", "string")
  .add("Token_1", "string")
  .add("Token_2", "string")
  .add("Token_3", "string")
  .add("Token_4", "string")
  .add("Token_5", "string")
  .add("Token_7", "string")
  .add("TokenEncryptionKey", "string")

// COMMAND ----------

val schema_21002 = new StructType()
  .add("PATIENT_ID", "string")
  .add("MAIL_RETAIL_CDE", "string")
  .add("PHCY_RX_NBR", "string")
  .add("RX_WRITTEN_DTE", "string")
  .add("SERVICED_DTE", "string")
  .add("PHCY_FILL_NBR", "string")
  .add("phcy_product_service_id", "string")
  .add("brand_nme", "string")
  .add("partial_fill_cde", "string")
  .add("fill_qty", "string")
  .add("fill_days_supply_qty", "string")
  .add("PAYMENT_TYPE", "string")
  .add("prescribed_rx_refills_qty", "string")
  .add("refills_remaining", "string")
  .add("daw_cde", "string")
  .add("LAST_NME", "string")
  .add("FIRST_NME", "string")
  .add("MIDDLE_NME", "string")
  .add("PRESCRIBER_QLFR_CDE", "string")
  .add("PRESCRIBER_ID", "string")
  .add("CITY_NME", "string")
  .add("STATE_OR_PROVINCE_CDE", "string")
  .add("POSTAL_CDE", "string")
  .add("VOICE_PHONE_NBR", "string")
  .add("NPI_NBR", "string")
  .add("POSTAL__CDE", "string")
  .add("e_prescribe", "string")
  .add("Claim_indicator", "string")
  .add("COMPOUND_CDE", "string")
  .add("PAY_COPAY_AMT", "string")
  .add("Diagnosis_Code", "string")
  .add("Medicare_D_Flag", "string")
  .add("sbmtd_unit_of_measure_cde", "string")
  .add("ADJUDN_SYSTEM_ENTRY_DTE_TIM", "string")
  .add("provider_service_type_cde", "string")
  .add("sbmtd_unit_dose_cde", "string")
  .add("PROVIDER_TAXONOMY", "string")
  .add("Medical_Qualifier_Code", "string")


// COMMAND ----------

val schema_21003 = new StructType()
  .add("patient id", "string")
  .add("medical claim header id", "string")
  .add("medical claim header src cde", "string")
  .add("transaction code", "string")
  .add("first serviced dte", "string")
  .add("last serviced dte", "string")
  .add("record type", "string")
  .add("claim record sequence number", "string")
  .add("medical code", "string")
  .add("medical qualifier code", "string")
  .add("place of service cde", "string")
  .add("cpt modifier cde", "string")
  .add("cpt modifier 2 cde", "string")
  .add("cpt modifier 3 cde", "string")
  .add("cpt modifier 4 cde", "string")
  .add("patient status cde", "string")
  .add("provider first name", "string")
  .add("provider middle name", "string")
  .add("provider last name", "string")
  .add("provider name suffix text", "string")
  .add("professional title text", "string")
  .add("npi nbr", "string")
  .add("provider street addr line 1", "string")
  .add("provider street addr line 2", "string")
  .add("provider city name", "string")
  .add("provider state or province code", "string")
  .add("postal cde", "string")
  .add("provider fax number", "string")
  .add("provider phone number", "string")

// COMMAND ----------

val schema_10101 = new StructType()
  .add("Change Healthcare Claim ID", "string")
  .add("Patient Date of Birth Hash", "string")
  .add("Patient Gender Hash", "string")
  .add("Date Of Service Hash", "string")
  .add("Token_1", "string")
  .add("Token_2", "string")
  .add("Token_3", "string")
  .add("Token_4", "string")
  .add("Token_17", "string")
  .add("Source FileName", "string")
  .add("TokenEncryptionKey", "string")

// COMMAND ----------

val schema_dv_clinical_2_0_0 = new StructType()
  .add("Patient ID", "string")
  .add("Unique Accession ID", "string")
  .add("Patient Date of Birth", "string")
  .add("Patient Gender", "string")
  .add("Patient State", "string")
  .add("Patient Bill Type", "string")
  .add("Diagnosis Codes", "string")
  .add("Diagnosis Descriptions", "string")
  .add("Laboratory Diagnosis", "string")
  .add("Billing Diagnosis Codes", "string")
  .add("Insurance Company ID", "string")
  .add("Insurance Company Name", "string")
  .add("Fasting", "string")
  .add("Performing Organization ID", "string")
  .add("Performing Organization Name", "string")
  .add("Performing Organization Address Line 1", "string")
  .add("Performing Organization Address Line 2", "string")
  .add("Performing Organization City", "string")
  .add("Performing Organization State", "string")
  .add("Performing Organization Zip Code", "string")
  .add("Analyzing Organization ID", "string")
  .add("Analyzing Organization Name", "string")
  .add("Analyzing Organization Address Line 1", "string")
  .add("Analyzing Organization Address Line 2", "string")
  .add("Analyzing Organization City", "string")
  .add("Analyzing Organization State", "string")
  .add("Analyzing Organization Zip Code", "string")
  .add("Receiving Organization ID", "string")
  .add("Receiving Organization Name", "string")
  .add("Receiving Organization Address Line 1", "string")
  .add("Receiving Organization Address Line 2", "string")
  .add("Receiving Organization City", "string")
  .add("Receiving Organization State", "string")
  .add("Receiving Organization Zip Code", "string")
  .add("Ordering Practice Name", "string")
  .add("Ordering Practice Lab Account Name", "string")
  .add("Ordering Practice Lab Account Number", "string")
  .add("Ordering Practice Address Line 1", "string")
  .add("Ordering Practice Address Line 2", "string")
  .add("Ordering Practice City", "string")
  .add("Ordering Practice State", "string")
  .add("Ordering Practice Zip Code", "string")
  .add("Ordering Provider Alternate ID Type", "string")
  .add("Ordering Provider Alternate ID", "string")
  .add("Ordering Provider NPI Number", "string")
  .add("Ordering Provider First Name", "string")
  .add("Ordering Provider Last Name", "string")
  .add("Ordering Provider Middle Initial", "string")
  .add("Ordering Provider Suffix", "string")
  .add("Ordering Provider Degree", "string")
  .add("Ordering Provider Primary Specialty", "string")
  .add("Ordering Provider Secondary Specialty", "string")
  .add("Referring Practice Name", "string")
  .add("Referring Practice Address Line 1", "string")
  .add("Referring Practice Address Line 2", "string")
  .add("Referring Practice City", "string")
  .add("Referring Practice State", "string")
  .add("Referring Practice Zip Code", "string")
  .add("Referring Provider Alternate ID Type", "string")
  .add("Referring Provider Alternate ID", "string")
  .add("Referring Provider NPI Number", "string")
  .add("Referring Provider First Name", "string")
  .add("Referring Provider Middle Initial", "string")
  .add("Referring Provider Last Name", "string")
  .add("Referring Provider Suffix", "string")
  .add("Referring Provider Degree", "string")
  .add("Referring Provider Primary Specialty", "string")
  .add("Referring Provider Secondary Specialty", "string")
  .add("Unique Test Specimen ID", "string")
  .add("Test Result Status", "string")
  .add("Test Turnaround Time", "string")
  .add("Test Order Code", "string")
  .add("Test Order Name", "string")
  .add("Test Result Code", "string")
  .add("Test Result Name", "string")
  .add("Test Result LOINC Code", "string")
  .add("Test Result Value", "string")
  .add("Test Result Range", "string")
  .add("Test Result Abnormal Flag", "string")
  .add("Test Result Reference Range", "string")
  .add("Test Result Units of Measure", "string")
  .add("Test Result Comment Source", "string")
  .add("Test Result Comments", "string")
  .add("Test Priority", "string")
  .add("Test Specimen Collection Volume", "string")
  .add("Test Specimen Type", "string")
  .add("Test Specimen Source", "string")
  .add("Test Relevant Clinical Information", "string")
  .add("Test CPT Code", "string")
  .add("Parent Test Order Code", "string")
  .add("Parent Test Order Name", "string")
  .add("Embedded Result Attached", "string")
  .add("Total Amount Charged", "string")
  .add("Total Amount Paid", "string")
  .add("Test Transaction DateTime", "string")
  .add("Test Specimen Draw DateTime", "string")
  .add("Test Specimen Receipt DateTime", "string")
  .add("Test Specimen Analysis DateTime", "string")
  .add("Test Observation DateTime", "string")
  .add("Test Observation Reported DateTime", "string")
  .add("Result Copies To", "string")
  .add("Result Copies Type", "string")
  .add("Panel Order Code", "string")
  .add("Panel Order Name", "string")
  .add("Parent Panel Order Code", "string")
  .add("Parent Panel Order Name", "string")
  .add("Accession Number", "string")
  .add("Input Filename", "string")
  .add("Token_1", "string")
  .add("Token_2", "string")
  .add("Token_3", "string")
  .add("Token_4", "string")
  .add("Token_5", "string")
  .add("Token_16", "string")
  .add("Token_17", "string")
  .add("TokenEncryptionKey", "string")

// COMMAND ----------

val schema_dv_clinical_3_0_0 = new StructType()
.add("Unique Patient ID", "string")
.add("Unique Accession ID", "string")
.add("DateOfBirth", "string")
.add("Gender", "string")
.add("AddressUSState", "string")
.add("AddressUSZip", "string")
.add("Patient Bill Type", "string")
.add("Diagnosis Codes", "string")
.add("Diagnosis Descriptions", "string")
.add("Laboratory Diagnosis", "string")
.add("Billing Diagnosis Codes", "string")
.add("Insurance Company ID", "string")
.add("Insurance Company Name", "string")
.add("Insurance Company Type", "string")
.add("Fasting", "string")
.add("Performing Organization ID", "string")
.add("Performing Organization Name", "string")
.add("Performing Organization Address Line 1", "string")
.add("Performing Organization Address Line 2", "string")
.add("Performing Organization City", "string")
.add("Performing Organization State", "string")
.add("Performing Organization Zip Code", "string")
.add("Analyzing Organization ID", "string")
.add("Analyzing Organization Name", "string")
.add("Analyzing Organization Address Line 1", "string")
.add("Analyzing Organization Address Line 2", "string")
.add("Analyzing Organization City", "string")
.add("Analyzing Organization State", "string")
.add("Analyzing Organization Zip Code", "string")
.add("Receiving Organization ID", "string")
.add("Receiving Organization Name", "string")
.add("Receiving Organization Address Line 1", "string")
.add("Receiving Organization Address Line 2", "string")
.add("Receiving Organization City", "string")
.add("Receiving Organization State", "string")
.add("Receiving Organization Zip Code", "string")
.add("Ordering Practice Name", "string")
.add("Ordering Practice Lab Account Name", "string")
.add("Ordering Practice Lab Account Number", "string")
.add("Ordering Practice Address Line 1", "string")
.add("Ordering Practice Address Line 2", "string")
.add("Ordering Practice City", "string")
.add("Ordering Practice State", "string")
.add("Ordering Practice Zip Code", "string")
.add("Ordering Provider Alternate ID Type", "string")
.add("Ordering Provider Alternate ID", "string")
.add("Ordering Provider NPI Number", "string")
.add("Ordering Provider First Name", "string")
.add("Ordering Provider Last Name", "string")
.add("Ordering Provider Middle Initial", "string")
.add("Ordering Provider Suffix", "string")
.add("Ordering Provider Degree", "string")
.add("Ordering Provider Primary Specialty", "string")
.add("Ordering Provider Secondary Specialty", "string")
.add("Referring Practice Name", "string")
.add("Referring Practice Address Line 1", "string")
.add("Referring Practice Address Line 2", "string")
.add("Referring Practice City", "string")
.add("Referring Practice State", "string")
.add("Referring Practice Zip Code", "string")
.add("Referring Provider Alternate ID Type", "string")
.add("Referring Provider Alternate ID", "string")
.add("Referring Provider NPI Number", "string")
.add("Referring Provider First Name", "string")
.add("Referring Provider Middle Initial", "string")
.add("Referring Provider Last Name", "string")
.add("Referring Provider Suffix", "string")
.add("Referring Provider Degree", "string")
.add("Referring Provider Primary Specialty", "string")
.add("Referring Provider Secondary Specialty", "string")
.add("Unique Test Specimen ID", "string")
.add("Test Result Status", "string")
.add("Test Turnaround Time", "string")
.add("Test Order Code", "string")
.add("Test Order Name", "string")
.add("Test Result Code", "string")
.add("Test Result Name", "string")
.add("Test Result LOINC Code", "string")
.add("Test Result Value", "string")
.add("Test Result Range", "string")
.add("Test Result Abnormal Flag", "string")
.add("Test Result Reference Range", "string")
.add("Test Result Units of Measure", "string")
.add("Test Result Comment Source", "string")
.add("Test Result Comments", "string")
.add("Test Priority", "string")
.add("Test Specimen Collection Volume", "string")
.add("Test Specimen Type", "string")
.add("Test Specimen Source", "string")
.add("Test Specimen Prep Method", "string")
.add("Test Relevant Clinical Information", "string")
.add("Test CPT Code", "string")
.add("Parent Test Order Code", "string")
.add("Parent Test Order Name", "string")
.add("Embedded Result Attached", "string")
.add("Total Amount Charged", "string")
.add("Total Amount Paid", "string")
.add("Test Transaction DateTime", "string")
.add("Test Specimen Draw DateTime", "string")
.add("Test Specimen Receipt DateTime", "string")
.add("Test Specimen Analysis DateTime", "string")
.add("Test Observation DateTime", "string")
.add("Test Observation Reported DateTime", "string")
.add("Test Methodology", "string")
.add("Test Methodology Threshold", "string")
.add("Test Biomarker Threshold", "string")
.add("Test Classification", "string")
.add("Test Manufacturer", "string")
.add("Test Instrument", "string")
.add("Test Kit", "string")
.add("Result Copies To", "string")
.add("Result Copies Type", "string")
.add("Panel Order Code", "string")
.add("Panel Order Name", "string")
.add("Parent Panel Order Code", "string")
.add("Parent Panel Order Name", "string")
.add("Accession Number", "string")
.add("InputFilename", "string")
.add("Token_1", "string")
.add("Token_2", "string")
.add("Token_3", "string")
.add("Token_4", "string")
.add("Token_5", "string")
.add("Token_16", "string")
.add("Token_17", "string")
.add("TokenEncryptionKey", "string")

// COMMAND ----------


val schema_60100 = new StructType()
  .add("WH Link ID", "string")
  .add("DOB", "string")
  .add("Gender", "string")
  .add("State", "string")
  .add("Link Partner ID", "string")
  .add("Version ID", "string")
  .add("Project ID", "string")
  .add("Input Filename", "string")
  .add("Token_1", "string")
  .add("Token_2", "string")
  .add("Token_4", "string")
  .add("TokenEncryptionKey", "string")


val schema_60101= new StructType()
  .add("Experian ID", "string")
  .add("First Name", "string")
  .add("Last Name", "string")
  .add("DOB", "string")
  .add("Gender", "string")
  .add("State", "string")
  .add("filler6", "string")
  .add("filler7", "string")
  .add("Token_1", "string")
  .add("Token_2", "string")
  .add("Token_4", "string")
  .add("TokenEncryptionKey", "string")

// COMMAND ----------

val schema_10110 = schema_10100
val schema_10210_S = schema_10200_S
val schema_10210_C = schema_10200_C
val schema_10210_D = schema_10200_D
val schema_21011 = schema_21001
val schema_21012 = schema_21002
val schema_21013 = schema_21003

val schema_10111 = schema_10101
val schema_10201 = schema_10101
val schema_10211 = schema_10101

// COMMAND ----------

// MAGIC %md ##### Test Schemas

// COMMAND ----------

val schema_90001 = schema_10100
val schema_90002 = schema_10101

// COMMAND ----------

// MAGIC %md ##### GTC Schema

// COMMAND ----------

val schema_30013 = new StructType()
    .add("PatientID", "string")
    .add("BillTypeName", "string")
    .add("CreatedDate", "string")
    .add("AccessionID", "string")
    .add("CaseID", "string")
    .add("CaseNo", "string")
    .add("CreatedDate2", "string")
    .add("SignedDate", "string")
    .add("NPI", "string")
    .add("CollectionDate", "string")
    .add("ReceivedDate", "string")
    .add("BodySiteName", "string")
    .add("ComponentCode", "string")
    .add("DataValue", "string")
    .add("ComponentName", "string")
    .add("ComponentTypeName", "string")
    .add("GateName", "string")
    .add("GroupName", "string")
    .add("SpecimenTypeName", "string")
    .add("ValueType", "string")
    .add("DrFirstName", "string")
    .add("DoctorID", "string")
    .add("DrLastName", "string")
    .add("DrMiddleName", "string")
    .add("Title", "string")
    .add("DoctorTypeName", "string")
    .add("FacilityName", "string")
    .add("Address", "string")
    .add("City", "string")
    .add("Country", "string")
    .add("PostalCode", "string")
    .add("StateProvince", "string")
    .add("Description", "string")
    .add("DateOfBirth", "string")
    .add("Gender", "string")
    .add("MRN", "string")
    .add("ClinicalData", "string")
    .add("ClinicalHistory", "string")
    .add("Comment", "string")
    .add("ExternalAccessionID", "string")
    .add("RequisitionNumber", "string")
    .add("ModifiedDate", "string")
    .add("PCLabName", "string")
    .add("SignedUserCredential", "string")
    .add("SignedUserFirstName", "string")
    .add("SignedUserID", "string")
    .add("SignedUserLastName", "string")
    .add("SignedUserMiddleName", "string")
    .add("SpecimenDescription", "string")
    .add("SpecimenID", "string")
    .add("SpecimenLocation", "string")
    .add("SpecimenLocationID", "string")
    .add("SpecimenLocationType", "string")
    .add("SpecimenName", "string")
    .add("SpecimenProcedure", "string")
    .add("PanelMnemonic", "string")
    .add("PanelName", "string")
    .add("CPTDescription", "string")
    .add("PatientState", "string")
    .add("TestCode", "string")
    .add("TestName", "string")
    .add("TestOrderID", "string")
    .add("TestStatusCode", "string")
    .add("TestStatusMnemonic", "string")
    .add("TestStatusName", "string")
    .add("TestTypeName", "string")
    .add("CPTCode", "string")
    .add("token_1", "string")
    .add("token_2", "string")
    .add("token_3", "string")
    .add("token_4", "string")
    .add("token_17", "string")
    .add("token_encryption_key", "string")
    

// COMMAND ----------

// MAGIC %md ##### AcentrusRx Schema

// COMMAND ----------

//AcentrusRx patient hash file (Prognos_AcentrusRx)
val schema_30014 = new StructType()
  .add("PATIENT ID", "string")
  .add("GENDER", "string")
  .add("RACE", "string")
  .add("ETHNICITY", "string")
  .add("ICD-9-CM PRIMARY DIAGNOSIS RELATED TO CURRENT PRESCRIPTION ORDER", "string")
  .add("ICD-9-CM SECONDARY DIAGNOSIS RELATED TO CURRENT PRESCRIPTION ORDER", "string")
  .add("ICD-10-CM PRIMARY DIAGNOSIS RELATED TO CURRENT PRESCRIPTION ORDER", "string")
  .add("ICD-10-CM SECONDARY DIAGNOSIS RELATED TO CURRENT PRESCRIPTION ORDER", "string")
  .add("PRESCRIBER NPI NUMBER", "string")
  .add("PHARMACY NPI NUMBER", "string")
  .add("PRESCRIPTION NDC", "string")
  .add("FULL PRODUCT GENERIC NAME", "string")
  .add("PRESCRIPTION NUMBER", "string")
  .add("PRESCRIPTION WRITTEN DATE", "string")
  .add("TOTAL PRESCRIPTION REFILLS ALLOWED", "string")
  .add("REFILLS REMAINING", "string")
  .add("PRESCRIPTION TRANSFERRED TO", "string")
  .add("PRESCRIPTION TRANSFERRED FROM", "string")
  .add("DIRECTIONS", "string")
  .add("REMS MEDICATION GUIDE PROVIDED", "string")
  .add("REFERRAL DATE", "string")
  .add("REFERRAL RECEIPT DATE", "string")
  .add("REFERRAL COMPLETED DATE", "string")
  .add("REFERRAL NUMBER", "string")
  .add("REFERRAL STATUS CODE", "string")
  .add("REFERRAL STATUS DATE", "string")
  .add("TRANSACTION NUMBER", "string")
  .add("PHARMACY RECEIPT DATE", "string")
  .add("PRESCRIPTION TYPE", "string")
  .add("DISPENSE STATUS", "string")
  .add("DISPENSE STATUS DATE", "string")
  .add("DISPENSE QUANTITY", "string")
  .add("DAYS SUPPLY", "string")
  .add("PRIOR AUTHORIZATION REQUIRED", "string")
  .add("PRIOR AUTHORIZATION OBTAINED", "string")
  .add("PRIOR AUTHORIZATION NUMBER", "string")
  .add("SHIPPING DATE", "string")
  .add("SHIPPING ADDRESS 1", "string")
  .add("SHIPPING ADDRESS 2", "string")
  .add("SHIPPING CITY", "string")
  .add("SHIPPING STATE", "string")
  .add("SHIPPING ZIP CODE", "string")
  .add("SHIPPING CARRIER", "string")
  .add("SHIPPING CARRIER TRACKING NUMBER", "string")
  .add("PRIMARY PHARMACY PAYOR ID CODE", "string")
  .add("PRIMARY PHARMACY PAYOR PLAN PATIENT ID", "string")
  .add("PRIMARY PHARMACY PAYOR PERSON CODE", "string")
  .add("PRIMARY PHARMACY PAYOR BIN", "string")
  .add("PRIMARY PHARMACY PAYOR PCN", "string")
  .add("PRIMARY PHARMACY PAYOR GROUP NUMBER", "string")
  .add("PRIMARY PHARMACY PAYOR COPAY", "string")
  .add("PRIMARY PHARMACY PAYOR OUT OF POCKET (OOP) MAXIMUM", "string")
  .add("PRIMARY PHARMACY PAYOR OUT OF POCKET (OOP) AMOUNT PAID", "string")
  .add("SECONDARY PHARMACY PAYOR ID CODE", "string")
  .add("SECONDARY PHARMACY PAYOR PLAN PATIENT ID", "string")
  .add("SECONDARY PHARMACY PAYOR PERSON CODE", "string")
  .add("SECONDARY PHARMACY PAYOR BIN", "string")
  .add("SECONDARY PHARMACY PAYOR PCN", "string")
  .add("SECONDARY PHARMACY PAYOR GROUP NUMBER", "string")
  .add("SECONDARY PHARMACY PAYOR COPAY", "string")
  .add("SECONDARY PHARMACY PAYOR OUT OF POCKET (OOP) MAXIMUM", "string")
  .add("SECONDARY PHARMACY PAYOR OUT OF POCKET (OOP) AMOUNT PAID", "string")
  .add("PATIENT ASSISTANCE PROGRAM", "string")
  .add("PATIENT ASSISTANCE SOURCE", "string")
  .add("PATIENT ASSISTANCE AMOUNT", "string")
  .add("PRIMARY MEDICAL PAYOR PLAN CODE", "string")
  .add("PRIMARY MEDICAL PAYOR PLAN PATIENT ID", "string")
  .add("PRIMARY MEDICAL PAYOR PERSON CODE", "string")
  .add("PRIMARY MEDICAL PAYOR GROUP NUMBER", "string")
  .add("PRIOR AUTHORIZATION EFFECTIVE DATE", "string")
  .add("PRIOR AUTHORIZATION EXPIRATION DATE", "string")
  .add("PRESCRIPTION TRANSFER DATE", "string")
  .add("LAST UPDATE DATE", "string")
  .add("LAST RECORDED PATIENT HEIGHT RELATED TO CURRENT PRESCRIPTION ORDER", "string")
  .add("LAST RECORDED PATIENT WEIGHT RELATED TO CURRENT PRESCRIPTION ORDER", "string")

// COMMAND ----------

//AcentrusRx Datavant token hash files (Prognos-PHI)
val schema_30015 = new StructType()
  .add("FIRST NAME", "string")
  .add("LAST NAME", "string")
  .add("DATE OF BIRTH", "string")
  .add("GENDER", "string")
  .add("ADDRESS 1", "string")
  .add("ZIP CODE", "string")
  .add("PATIENT ID", "string")
  .add("Token 1", "string")
  .add("token_2", "string")
  .add("Token 3", "string")
  .add("Token 4", "string")
  .add("token_encryption_key", "string")

// COMMAND ----------

//AcentrusRx Prescriber files (Prognos_AcentrusRx_MDP)
val schema_30016 = new StructType()
  .add("HOSPITAL ASSIGNED PRESCRIBER ID", "string")
  .add("PRESCRIBER NPI NUMBER", "string")
  .add("PRESCRIBER DEA", "string")
  .add("PRESCRIBER HUB ID", "string")
  .add("PRESCRIBER LAST NAME", "string")
  .add("PRESCRIBER FIRST NAME", "string")
  .add("PRESCRIBER MIDDLE NAME", "string")
  .add("PRESCRIBER SUFFIX", "string")
  .add("PRESCRIBER GROUP PRACTICE ID", "string")
  .add("PRESCRIBER PRACTICE LOCATION NAME", "string")
  .add("PRESCRIBER LOCATION ADDRESS 1", "string")
  .add("PRESCRIBER LOCATION ADDRESS 2", "string")
  .add("PRESCRIBER CITY", "string")
  .add("PRESCRIBER STATE", "string")
  .add("PRESCRIBER ZIP CODE", "string")
  .add("PRESCRIBER PHONE", "string")
  .add("PRESCRIBER FAX", "string")

// COMMAND ----------

//AcentrusRx Pharmacy files (Prognos_AcentrusRx_SRX)
val schema_30017 = new StructType()
  .add("PHARMACY NPI NUMBER", "string")
  .add("PHARMACY NAME", "string")
  .add("PHARMACY SUB NAME", "string")
  .add("PHARMACY NUMBER", "string")
  .add("PHARMACY NCPDP", "string")
  .add("PHARMACY ADDRESS 1", "string")
  .add("PHARMACY ADDRESS 2", "string")
  .add("PHARMACY CITY", "string")
  .add("PHARMACY STATE", "string")
  .add("PHARMACY ZIP CODE", "string")
  .add("PHARMACY PHONE", "string")
  .add("PHARMACY FAX", "string")

// COMMAND ----------

//AcentrusRx Payor files (Prognos_AcentrusRx_PAY)
val schema_30018 = new StructType()
  .add("PAYOR ID CODE", "string")
  .add("PAYOR PLAN NAME", "string")
  .add("PAYOR PLAN SEGMENT", "string")
  .add("PAYOR PLAN PRODUCT LINE", "string")
  .add("PAYOR PLAN TYPE CODE", "string")

// COMMAND ----------

//AcentrusRx Patient files (Prognos_AcentrusRx_PAF)
val schema_30019= new StructType()
  .add("ENCOUNTER ID", "string")
  .add("ADHERENCE CALL NUMBER", "string")
  .add("ADHERENCE CALL TYPE", "string")
  .add("ADHERENCE CALL DATE", "string")
  .add("PRESCRIPTION NUMBER", "string")
  .add("PATIENT ID", "string")

// COMMAND ----------

// MAGIC %md ##### Company K Schema

// COMMAND ----------

val schema_32600 = new StructType()
  .add("ReferenceID", "string")
  .add("token_encryption_key", "string")
  .add("token_1", "string")
  .add("token_2", "string")
  .add("token_3", "string")
  .add("token_4", "string")
  .add("token_5", "string")
  .add("token_16", "string")
  .add("token_17", "string")

// COMMAND ----------

val schema_32601 = new StructType()
  .add("Unique Patient ID", "string")
  .add("Unique Accession ID", "string")
  .add("Patient First Name", "string")
  .add("Patient Last Name", "string")
  .add("Patient Middle Name", "string")
  .add("Patient Address Line 1", "string")
  .add("Patient Address Line 2", "string")
  .add("Patient Home Phone", "string")
  .add("Patient Work Phone", "string")
  .add("Patient Social Security Number", "string")
  .add("Patient Date of Birth", "string")
  .add("Patient Gender", "string")
  .add("Patient City", "string")
  .add("Patient State", "string")
  .add("Patient ZIP Code", "string")
  .add("Patient Bill Type", "string")
  .add("Diagnosis Codes", "string")
  .add("Diagnosis Descriptions", "string")
  .add("Laboratory Diagnosis", "string")
  .add("Billing Diagnosis Codes", "string")
  .add("Insurance Company ID", "string")
  .add("Insurance Company Name", "string")
  .add("Insurance Company Type", "string")
  .add("Fasting", "string")
  .add("Performing Organization ID", "string")
  .add("Performing Organization Name", "string")
  .add("Performing Organization Address Line 1", "string")
  .add("Performing Organization Address Line 2", "string")
  .add("Performing Organization City", "string")
  .add("Performing Organization State", "string")
  .add("Performing Organization Zip Code", "string")
  .add("Analyzing Organization ID", "string")
  .add("Analyzing Organization Name", "string")
  .add("Analyzing Organization Address Line 1", "string")
  .add("Analyzing Organization Address Line 2", "string")
  .add("Analyzing Organization City", "string")
  .add("Analyzing Organization State", "string")
  .add("Analyzing Organization Zip Code", "string")
  .add("Receiving Organization ID", "string")
  .add("Receiving Organization Name", "string")
  .add("Receiving Organization Address Line 1", "string")
  .add("Receiving Organization Address Line 2", "string")
  .add("Receiving Organization City", "string")
  .add("Receiving Organization State", "string")
  .add("Receiving Organization Zip Code", "string")
  .add("Ordering Practice Name", "string")
  .add("Ordering Practice Lab Account Name", "string")
  .add("Ordering Practice Lab Account Number", "string")
  .add("Ordering Practice Address Line 1", "string")
  .add("Ordering Practice Address Line 2", "string")
  .add("Ordering Practice City", "string")
  .add("Ordering Practice State", "string")
  .add("Ordering Practice Zip Code", "string")
  .add("Ordering Provider Alternate ID Type", "string")
  .add("Ordering Provider Alternate ID", "string")
  .add("Ordering Provider NPI Number", "string")
  .add("Ordering Provider First Name", "string")
  .add("Ordering Provider Last Name", "string")
  .add("Ordering Provider Middle Initial", "string")
  .add("Ordering Provider Suffix", "string")
  .add("Ordering Provider Degree", "string")
  .add("Ordering Provider Primary Specialty", "string")
  .add("Ordering Provider Secondary Specialty", "string")
  .add("Referring Practice Name", "string")
  .add("Referring Practice Address Line 1", "string")
  .add("Referring Practice Address Line 2", "string")
  .add("Referring Practice City", "string")
  .add("Referring Practice State", "string")
  .add("Referring Practice Zip Code", "string")
  .add("Referring Provider Alternate ID Type", "string")
  .add("Referring Provider Alternate ID", "string")
  .add("Referring Provider NPI Number", "string")
  .add("Referring Provider First Name", "string")
  .add("Referring Provider Middle Initial", "string")
  .add("Referring Provider Last Name", "string")
  .add("Referring Provider Suffix", "string")
  .add("Referring Provider Degree", "string")
  .add("Referring Provider Primary Specialty", "string")
  .add("Referring Provider Secondary Specialty", "string")
  .add("Unique Test Specimen ID", "string")
  .add("Test Result Status", "string")
  .add("Test Turnaround Time", "string")
  .add("Test Order Code", "string")
  .add("Test Order Name", "string")
  .add("Test Result Code", "string")
  .add("Test Result Name", "string")
  .add("Test Result LOINC Code", "string")
  .add("Test Result Value", "string")
  .add("Test Result Range", "string")
  .add("Test Result Abnormal Flag", "string")
  .add("Test Result Reference Range", "string")
  .add("Test Result Units of Measure", "string")
  .add("Test Result Comment Source", "string")
  .add("Test Result Comments", "string")
  .add("Test Priority", "string")
  .add("Test Specimen Collection Volume", "string")
  .add("Test Specimen Type", "string")
  .add("Test Specimen Source", "string")
  .add("Test Specimen Prep Method", "string")
  .add("Test Relevant Clinical Information", "string")
  .add("Test CPT Code", "string")
  .add("Parent Test Order Code", "string")
  .add("Parent Test Order Name", "string")
  .add("Embedded Result Attached", "string")
  .add("Total Amount Charged", "string")
  .add("Total Amount Paid", "string")
  .add("Test Transaction DateTime", "string")
  .add("Test Specimen Draw DateTime", "string")
  .add("Test Specimen Receipt DateTime", "string")
  .add("Test Specimen Analysis DateTime", "string")
  .add("Test Observation DateTime", "string")
  .add("Test Observation Reported DateTime", "string")
  .add("Test Methodology", "string")
  .add("Test Methodology Threshold", "string")
  .add("Test Biomarker Threshold", "string")
  .add("Test Classification", "string")
  .add("Test Manufacturer", "string")
  .add("Test Instrument", "string")
  .add("Test Kit", "string")
  .add("Result Copies To", "string")
  .add("Result Copies Type", "string")
  .add("Panel Order Code", "string")
  .add("Panel Order Name", "string")
  .add("Parent Panel Order Code", "string")
  .add("Parent Panel Order Name", "string")
  .add("Accession Number", "string")
  .add("Input Filename", "string")
  .add("Sequence Number", "string")
  .add("Order Result Flag", "string")

// COMMAND ----------

val schema_32602 = new StructType()
  .add("Performing Organization Name", "string")
  .add("TestID", "string")
  .add("TestOrderCode", "string")
  .add("TestOrderName", "string")
  .add("ResultCode", "string")
  .add("ResultName", "string")
  .add("ResultLOINCCode", "string")
  .add("Units", "string")
  .add("TestDate", "string")

// COMMAND ----------

val schema_32603 = new StructType()
  .add("performing_organization_name", "string")
  .add("client_name", "string")

// COMMAND ----------

// MAGIC %md ##### Data Partner X Schema

// COMMAND ----------

//Data Partner X Datavant token files
val schema_30020 = new StructType()
  .add("claim_id", "string")
  .add("state", "string")
  .add("zip", "string")
  .add("dob", "string")
  .add("gender", "string")
  .add("token_1", "string")
  .add("token_2", "string")
  .add("token_3", "string")
  .add("token_4", "string")
  .add("token_12", "string")
  .add("token_17", "string")
  .add("token_encryption_key", "string")

// COMMAND ----------

//Data Partner X rx files
val schema_30021 = new StructType()
  .add("Claim_ClaimIdentifier","string")
  .add("Prescription_FillDate","string")
  .add("Prescription_PrescriptionNumber","string")
  .add("Prescription_WrittenDate","string")
  .add("Prescription_TransmissionDate","string")
  .add("Prescription_TransactionCode","string")
  .add("Prescription_QuantityPrescribed","string")
  .add("Prescription_QuantityDispensed","string")
  .add("Prescription_DaysSupply","string")
  .add("Prescription_RefillNumber","string")
  .add("Prescription_NumberOfRefillsAuthorized","string")
  .add("Prescription_DispensedAsWrittenCode","string")
  .add("Prescription_LevelOfService","string")
  .add("Prescription_OriginCode","string")
  .add("Prescription_PriorAuthorizationTypeCode","string")
  .add("Prescription_SubmissionClarificationCode","string")
  .add("Patient_ObfuscatedPersonID","string")
  .add("Pharmacy_ObfuscatedProviderID","string")
  .add("Pharmacy_Address_PostalCode","string")
  .add("HCP_Prescriber_FirstName","string")
  .add("HCP_Prescriber_LastName","string")
  .add("HCP_Prescriber_StateIssuedLicenseNumber","string")
  .add("HCP_Prescriber_NationalProviderIdentifier","string")
  .add("HCP_Prescriber_DEARegistrationNumber","string")
  .add("HCP_Prescriber_QualifiedProviderID","string")
  .add("HCP_Prescriber_QualifiedProviderID_Qualifier","string")
  .add("HCP_Prescriber_SpecialtyCode","string")
  .add("HCP_Prescriber_Address_Street1","string")
  .add("HCP_Prescriber_Address_Street2","string")
  .add("HCP_Prescriber_Address_City","string")
  .add("HCP_Prescriber_Address_StateCode","string")
  .add("HCP_Prescriber_Address_PostalCode","string")
  .add("Drug_PrimaryDispensedNDC","string")
  .add("Drug_OriginallyPrescribedNDC","string")
  .add("Drug_UnitDoseIndicator","string")
  .add("Payer_ProcessorIdentifier","string")
  .add("Payer_ProcessorControlNumber","string")
  .add("Payer_Plan_InsurancePlanCode","string")
  .add("Payer_Plan_InsurancePlanName","string")
  .add("Payer_QualifiedPayerID","string")
  .add("Payer_QualifiedPayerID_Qualifier","string")
  .add("Payer_OtherCoverageCode","string")
  .add("Payer_OtherPayer_Count","string")
  .add("Money_TransactionPrice_Claim","string")
  .add("Money_PatientResponsibility_Claim_Paid","string")
  .add("Money_PatientResponsibility_Claim_Submitted","string")
  .add("Money_PatientResponsibility_Claim_CopayAmount","string")
  .add("Money_PatientResponsibility_DeductibleAmountAccumulated","string")
  .add("Money_PatientResponsibility_DeductibleAmountApplied","string")
  .add("Money_PatientResponsibility_DeductibleAmountRemaining","string")
  .add("Money_PayerReceivableAmount_Claim_AdjudicatedAmount","string")
  .add("Money_DispensingFee_Claim_Paid","string")
  .add("Money_DispensingFee_Claim_Submitted","string")
  .add("Money_IngredientCost_Claim_Paid","string")
  .add("Money_IngredientCost_Claim_Submitted","string")
  .add("Money_IncentiveAmount_Claim_Paid","string")
  .add("Money_IncentiveAmount_Claim_Submitted","string")
  .add("Money_ProfessionalServiceFee_Claim_Paid","string")
  .add("Money_ProfessionalServiceFee_Claim_Submitted","string")
  .add("Money_UsualAndCustomaryPrice","string")
  .add("Money_BasisOfReimbursement","string")
  .add("Money_CostBasisResponse","string")
  .add("Money_RemainingBenefitAmount","string")
  .add("Money_AmountExceedingPeriodicBenefitMaximum","string")
  .add("Money_AttributedAmount_ProductSelectionBrandDrug","string")
  .add("Money_OtherAmount_Claim_Submitted","string")
  .add("Money_OtherPayer_AmountRecognized","string")
  .add("Money_SecondaryAmount_Paid","string")
  .add("Money_TaxExemptIndicator","string")
  .add("OtherInformation_HCP_PrimaryCareProvider_QualifiedProviderID","string")
  .add("OtherInformation_HCP_PrimaryCareProvider_QualifiedProviderID_Qualifier","string")
  .add("OtherInformation_ProfessionalServiceCode","string")
  .add("OtherInformation_QualifiedDiagnosisCode","string")
  .add("OtherInformation_QualifiedDiagnosisCode_Qualifier","string")
  .add("OtherInformation_ReasonForServiceCode","string")
  .add("OtherInformation_ResultOfServiceCode","string")
  .add("Payer_Plan_GroupInsuranceNumber","string")
  .add("Payer_PayerName","string")
  .add("Money_GrossAmountDue","string")
  .add("Money_OtherPayerAmountPaid","string")
  .add("Payer_OtherPayerID","string")
  .add("Payer_OtherPayerIDQualifier","string")
  .add("Prescription_OtherPayerDate","string")
  .add("Prescription_TransmissionTime","string")
  .add("Record_InsertedDate","string")

// COMMAND ----------

// MAGIC %md ##### Oncohub Schemas

// COMMAND ----------

val schema_1701143194 = new StructType()
.add("FIRST_NAME", "string")
.add("LAST_NAME", "string")
.add("PATIENT_DOB", "string")
.add("PATIENT_SEX", "string")
.add("PATIENT_ZIP", "string")
.add("PATIENT_ST_ADDR1", "string")
.add("PATIENT_ST_ADDR2", "string")
.add("PATIENT_CITY", "string")
.add("PATIENT_ST", "string")
.add("MEMBER_ID_HASH", "string")
.add("PATIENT_ID_HASH", "string")
.add("GROUP_ID_HASH", "string")
.add("SPECIMEN_NUMBER", "string")
.add("token_1", "string")
.add("token_2", "string")
.add("token_3", "string")
.add("token_4", "string")
.add("token_17", "string")
.add("input_filename", "string")
.add("token_encryption_key", "string")

// COMMAND ----------

val schema_1701143124 = new StructType()
.add("specimen_number", "string")
.add("reported_date", "string")
.add("account_name_1", "string")
.add("account_address_line_1", "string")
.add("account_city", "string")
.add("account_state", "string")
.add("account_zip", "string")
.add("provider_first_name", "string")
.add("provider_last_name", "string")
.add("provider_middle_name", "string")
.add("provider_npi", "string")
.add("curated_specimen_site", "string")
.add("curated_specimen_type", "string")
.add("curated_clinical_history", "string")
.add("curated_topography", "string")
.add("curated_morphology", "string")
.add("tumor_stage", "string")
.add("tissue_source", "string")
.add("lab_methodology", "string")
.add("ordered_test_name", "string")
.add("marker_name", "string")
.add("failure_reason", "string")
.add("marker_result", "string")
.add("marker_sub_result", "string")
.add("result_type", "string")
.add("c_dot_name", "string")
.add("p_dot_name", "string")
.add("accessioned_icd10_codes", "string")
.add("result_status", "string")

// COMMAND ----------

// MAGIC %md ##### Guardant Schema

// COMMAND ----------

val schema_30022 = new StructType()
.add("dv_token_1", "string")
.add("dv_token_2", "string")
.add("patient_state", "string")
.add("gh_yob", "string")
.add("gh_patientgender", "string")
.add("practice_state", "string")
.add("first_name_of_provider", "string")
.add("last_name_of_provider", "string")
.add("national_provider_identifier", "string")
.add("provider_specialty", "string")
.add("bloodcolldate", "string")
.add("receiveddate", "string")
.add("finalreportdate", "string")
.add("accessiondate", "string")
.add("product", "string")
.add("gene", "string")
.add("alteration_of_interest", "string")
.add("percentage", "string")
.add("icdcode_1", "string")
.add("icdcode_2", "string")
.add("icdcode_3", "string")
.add("icdcode_4", "string")
.add("icdcode_5", "string")
.add("icdcode_6", "string")
.add("icdcode_7", "string")
.add("icdcode_8", "string")
.add("icdcode_9", "string")
.add("icdcode_10","string")
.add("data_use_case_allowed", "string")
.add("cancer_category", "string")
.add("record_line_of_therapy", "string")
.add("practice_setting", "string")
.add("practice_name", "string")
.add("practice_address", "string")
.add("practice_city", "string")
.add("practice_zip_code", "string")
.add("sample_type", "string")

// COMMAND ----------

// MAGIC %md ##### Invitae Schema

// COMMAND ----------

val schema_1704385286 = new StructType()
.add("Original Report Released Date","string")
.add("Patient ID (Hashed)","string")
.add("Age at Testing","string")
.add("Current Patient Age (if living)","string")
.add("Sex Assigned at Birth","string")
.add("Ethnicity","string")
.add("ICD10 Codes","string")
.add("Institution Name","string")
.add("Institution Country","string")
.add("Institution State","string")
.add("MSA Name","string")
.add("Institution ZIP","string")
.add("Gene","string")
.add("Variant","string")
.add("Zygosity","string")
.add("Classification","string")
.add("Molecular Diagnosis","string")
.add("Chromosome","string")
.add("Position - Start","string")
.add("Position - End","string")
.add("Ref","string")
.add("Alt","string")
.add("Panel Type","string")
.add("Panel Name","string")
.add("NPI","string")
.add("Year of Birth","string")
.add("token_1","string")
.add("token_2","string")
.add("token_3","string")
.add("token_4","string")
.add("token_17","string")

// COMMAND ----------

// MAGIC %md ##### Bioreference NGS Schema

// COMMAND ----------

val schema_1705006446 = new StructType()
.add("Unique Patient ID","string")
.add("Unique Accession ID","string")
.add("Patient Date of Birth","string")
.add("Patient Gender","string")
.add("Patient State","string")
.add("Patient Zip Code","string")
.add("Laboratory Diagnosis","string")
.add("Billing Diagnosis Codes","string")
.add("Ordering Practice Name","string")
.add("Ordering Practice Address Line 1","string")
.add("Ordering Practice City","string")
.add("Ordering Practice State","string")
.add("Ordering Practice Zip Code","string")
.add("Ordering Provider NPI","string")
.add("Ordering Provider First Name","string")
.add("Ordering Provider Last Name","string")
.add("Ordering Provider Primary Specialty","string")
.add("Test Specimen Site","string")
.add("Test Specimen Receipt DateTime","string")
.add("Test Observation Reported DateTime","string")
.add("Test Platform","string")
.add("Test Methodology","string")
.add("Test Modality","string")
.add("Marker Name","string")
.add("Marker Result","string")
.add("HGVS","string")
.add("Alteration Type","string")
.add("Summary Text","string")
.add("Performed Test Code","string")
.add("Performed Test Name","string")
.add("TMB","string")
.add("MSI","string")
.add("Token_1","string")
.add("Token_2","string")
.add("Token_3","string")
.add("Token_4","string")
.add("Token_5","string")
.add("Token_16","string")
.add("Token_17","string")
.add("TokenEncryptionKey","string")

// COMMAND ----------

// MAGIC %md ##### Apollo Lab Data Schemas

// COMMAND ----------

val schema_apollo_patient = new StructType()
  .add("ACCN_ID", "string")
  .add("DOS_ID", "string")
  .add("LAB_ID", "string")
  .add("TOKEN_1", "string")
  .add("TOKEN_2", "string")
  .add("TOKEN_3", "string")
  .add("TOKEN_6", "string")
  .add("ADDRESS2", "string")
  .add("CITY", "string")
  .add("STATE", "string")
  .add("ZIP_CODE", "string")
  .add("DATE_OF_BIRTH", "string")
  .add("PATIENT_AGE", "string")
  .add("GENDER", "string")

// Apollo changed the schema for SOW 2 and appears to be using this new one moving fwd.
// Left some names the same and aligned with previous style to remain more compatible
// with existing work.
val schema_apollo_patient_v2 = new StructType()
  .add("ACCN_ID", "string")       // ACCN_ID
  .add("DOS_ID", "string")        // DOSID
  .add("LAB_ID", "string")        // LABID
  .add("TOKEN_1", "string")       // TOKEN1
  .add("TOKEN_2", "string")       // TOKEN2
  .add("TOKEN_3", "string")       // TOKEN3
  .add("TOKEN_6", "string")       // TOKEN6
  .add("TOKEN_10", "string")      // TOKEN10
  .add("TOKEN_11", "string")      // TOKEN11
  .add("STATE", "string")         // ADDRESSUSSTATE
  .add("ZIP_CODE", "string")      // ADDRESSUSZIP
  .add("DATE_OF_BIRTH", "string") // DATEOFBIRTH
  .add("NULL_13", "string")       // NULL_13
  .add("GENDER", "string")        // GENDER


// COMMAND ----------

val schema_apollo_data = new StructType()
  .add("ACCN_ID", "string")
  .add("DOS_301", "string")
  .add("LAB_ID", "string")
  .add("DATE_OF_SERVICE", "string")
  .add("DATE_COLLECTED", "string")
  .add("HIPAA_ZIP_CODE", "string")
  .add("HIPAA_DATE_OF_BIRTH", "string")
  .add("HIPAA_PATIENT_AGE", "string")
  .add("GENDER", "string")
  .add("QBS_PAYOR_CD", "string")
  .add("INSURANCE_BILLING_TYPE", "string")
  .add("LOCAL_PROFILE_CODE", "string")
  .add("STANDARD_PROFILE_CODE", "string")
  .add("PROFILE_NAME", "string")
  .add("LOCAL_ORDER_CODE", "string")
  .add("STANDARD_ORDER_CODE", "string")
  .add("ORDER_NAME", "string")
  .add("ORDERING_ACCOUNT_ID", "string")
  .add("ORDERING_ACCOUNT_NAME", "string")
  .add("ORDERING_ACCOUNT_ADDR1", "string")
  .add("ORDERING_ACCOUNT_ADDR2", "string")
  .add("ORDERING_ACCOUNT_CITY", "string")
  .add("ORDERING_ACCOUNT_STATE", "string")
  .add("ORDERING_ACCOUNT_ZIP_CODE", "string")
  .add("PHYSICIAN_NAME", "string")
  .add("UPIN", "string")
  .add("NPI", "string")
  .add("CLIENT_MARKET_TYPE", "string")
  .add("CLIENT_SPECIALTY", "string")
  .add("DIAGNOSIS_CODE", "string")
  .add("ICD_CODESET_IND", "string")
  .add("LOINC_CODE", "string")
  .add("LOCAL_RESULT_CODE", "string")
  .add("RESULT_NAME", "string")
  .add("RESULT_VALUE", "string")
  .add("RESULTS_UNITS", "string")
  .add("REFERENCE_RANGE_LOW", "string")
  .add("REFERENCE_RANGE_HIGH", "string")
  .add("REFERENCE_RANGE_ALPHA", "string")
  .add("ABNORMAL_FLAG", "string")
  .add("RESULT_COMMENTS", "string")
  .add("FINAL_REPORT_DATE", "string")
  .add("FASTING_STATUS", "string")

// COMMAND ----------

// MAGIC %md ##### LC SF Lab Data Schemas

// COMMAND ----------

val schema_lc_sf_deid = new StructType()
  .add("FIRST_NAME", "string")
  .add("LAST_NAME", "string")
  .add("PATIENT_DOB", "string")
  .add("PATIENT_SEX", "string")
  .add("PATIENT_ZIP", "string")
  .add("PATIENT_ST_ADDR1", "string")
  .add("PATIENT_ST_ADDR2", "string")
  .add("PATIENT_CITY", "string")
  .add("PATIENT_ST", "string")
  .add("MEMBER_ID_HASH", "string")
  .add("PATIENT_ID_HASH", "string")
  .add("GROUP_ID_HASH", "string")
  .add("SPECIMEN_NUMBER", "string")
  .add("DRAW_YEAR", "string")
  .add("token_1", "string")
  .add("token_2", "string")
  .add("token_3", "string")
  .add("token_4", "string")
  .add("token_17", "string")
  .add("input_filename", "string")
  .add("token_encryption_key", "string")

// COMMAND ----------

val schema_lc_sf_results = new StructType()
  .add("TEST_NAME", "string")
  .add("TEST_NUMBER", "string")
  .add("LOINC_CODE", "string")
  .add("NORMAL_DEC_LOW", "string")
  .add("NORMAL_DEC_HIGH", "string")
  .add("RESULT_DEC", "string")
  .add("RESULT_ABN_CODE", "string")
  .add("RESULT_ABBREV", "string")
  .add("PAT_DOS", "string")
  .add("TEST_OBSERVATION_REPORTED_DATETIME", "string")
  .add("PERF_LAB_CODE", "string")
  .add("INVOICE_DATE", "string")
  .add("RSLT_COMMENTS", "string")
  .add("TEST_ORDERED_CODE", "string")
  .add("TEST_ORDERED_NAME", "string")
  .add("NPI", "string")
  .add("ORDERING_PROVIDER_FIRST_NAME", "string")
  .add("ORDERING_PROVIDER_LAST_NAME", "string")
  .add("SPECIALTY_CODE", "string")
  .add("ORDERING_PRACTICE_LAB_ACCOUNT_NAME", "string")
  .add("ORDERING_PRACTICE_LAB_ACCOUNT_NUMBER", "string")
  .add("ORDERING_PRACTICE_ADDRESS_LINE_1", "string")
  .add("ORDERING_PRACTICE_CITY", "string")
  .add("ORDERING_PRACTICE_STATE", "string")
  .add("ORDERING_PRACTICE_ZIP_CODE", "string")
  .add("SPECIMEN_NUMBER", "string")
  .add("DRAW_YEAR", "string")
  .add("ICD_CODE_1", "string")
  .add("ICD_CODE_IND_1", "string")
  .add("ICD_CODE_2", "string")
  .add("ICD_CODE_IND_2", "string")
  .add("ICD_CODE_3", "string")
  .add("ICD_CODE_IND_3", "string")
  .add("ICD_CODE_4", "string")
  .add("ICD_CODE_IND_4", "string")
  .add("ICD_CODE_5", "string")
  .add("ICD_CODE_IND_5", "string")
  .add("ICD_CODE_6", "string")
  .add("ICD_CODE_IND_6", "string")

// COMMAND ----------

val schema_lc_sf_historical_icds = new StructType()
  .add("specimen_number", "string")
  .add("draw_year", "string")
  .add("diagnosis_codes", "string")

// COMMAND ----------

val schema_lc_sf_results_full_icds = new StructType()
  .add("TEST_NAME", "string")
  .add("TEST_NUMBER", "string")
  .add("LOINC_CODE", "string")
  .add("NORMAL_DEC_LOW", "string")
  .add("NORMAL_DEC_HIGH", "string")
  .add("RESULT_DEC", "string")
  .add("RESULT_ABN_CODE", "string")
  .add("RESULT_ABBREV", "string")
  .add("PAT_DOS", "string")
  .add("TEST_OBSERVATION_REPORTED_DATETIME", "string")
  .add("PERF_LAB_CODE", "string")
  .add("INVOICE_DATE", "string")
  .add("RSLT_COMMENTS", "string")
  .add("TEST_ORDERED_CODE", "string")
  .add("TEST_ORDERED_NAME", "string")
  .add("NPI", "string")
  .add("ORDERING_PROVIDER_FIRST_NAME", "string")
  .add("ORDERING_PROVIDER_LAST_NAME", "string")
  .add("SPECIALTY_CODE", "string")
  .add("ORDERING_PRACTICE_LAB_ACCOUNT_NAME", "string")
  .add("ORDERING_PRACTICE_LAB_ACCOUNT_NUMBER", "string")
  .add("ORDERING_PRACTICE_ADDRESS_LINE_1", "string")
  .add("ORDERING_PRACTICE_CITY", "string")
  .add("ORDERING_PRACTICE_STATE", "string")
  .add("ORDERING_PRACTICE_ZIP_CODE", "string")
  .add("SPECIMEN_NUMBER", "string")
  .add("DRAW_YEAR", "string")
  .add("ICD_CODE_1", "string")
  .add("ICD_CODE_IND_1", "string")
  .add("ICD_CODE_2", "string")
  .add("ICD_CODE_IND_2", "string")
  .add("ICD_CODE_3", "string")
  .add("ICD_CODE_IND_3", "string")
  .add("ICD_CODE_4", "string")
  .add("ICD_CODE_IND_4", "string")
  .add("ICD_CODE_5", "string")
  .add("ICD_CODE_IND_5", "string")
  .add("ICD_CODE_6", "string")
  .add("ICD_CODE_IND_6", "string")
  .add("diagnosis_codes", "string")

// COMMAND ----------

val schema_lc_sf_results_uom = new StructType()
  .add("TEST_NAME", "string")
  .add("TEST_NUMBER", "string")
  .add("LOINC_CODE", "string")
  .add("NORMAL_DEC_LOW", "string")
  .add("NORMAL_DEC_HIGH", "string")
  .add("RESULT_DEC", "string")
  .add("RESULT_ABN_CODE", "string")
  .add("RESULT_ABBREV", "string")
  .add("PAT_DOS", "string")
  .add("TEST_OBSERVATION_REPORTED_DATETIME", "string")
  .add("PERF_LAB_CODE", "string")
  .add("INVOICE_DATE", "string")
  .add("RSLT_COMMENTS", "string")
  .add("TEST_ORDERED_CODE", "string")
  .add("TEST_ORDERED_NAME", "string")
  .add("NPI", "string")
  .add("ORDERING_PROVIDER_FIRST_NAME", "string")
  .add("ORDERING_PROVIDER_LAST_NAME", "string")
  .add("SPECIALTY_CODE", "string")
  .add("ORDERING_PRACTICE_LAB_ACCOUNT_NAME", "string")
  .add("ORDERING_PRACTICE_LAB_ACCOUNT_NUMBER", "string")
  .add("ORDERING_PRACTICE_ADDRESS_LINE_1", "string")
  .add("ORDERING_PRACTICE_CITY", "string")
  .add("ORDERING_PRACTICE_STATE", "string")
  .add("ORDERING_PRACTICE_ZIP_CODE", "string")
  .add("SPECIMEN_NUMBER", "string")
  .add("DRAW_YEAR", "string")
  .add("ICD_CODE_1", "string")
  .add("ICD_CODE_IND_1", "string")
  .add("ICD_CODE_2", "string")
  .add("ICD_CODE_IND_2", "string")
  .add("ICD_CODE_3", "string")
  .add("ICD_CODE_IND_3", "string")
  .add("ICD_CODE_4", "string")
  .add("ICD_CODE_IND_4", "string")
  .add("ICD_CODE_5", "string")
  .add("ICD_CODE_IND_5", "string")
  .add("ICD_CODE_6", "string")
  .add("ICD_CODE_IND_6", "string")
  .add("diagnosis_codes", "string")
  .add("TEST_UNITS", "string")

// COMMAND ----------

val schema_lc_sf_supplemental_uom = new StructType()
  .add("SPECIMEN_NUMBER", "string")
  .add("DRAW_YEAR", "string")
  .add("TEST_ORDERED_CODE", "string")
  .add("TEST_ORDERED_NAME", "string")
  .add("TEST_NAME", "string")
  .add("TEST_NUMBER", "string")
  .add("LOINC_CODE", "string")
  .add("TEST_UNITS", "string")

// COMMAND ----------

// MAGIC %md
// MAGIC **GeneDx schema**

// COMMAND ----------

val schema_1750704167 = new StructType()
  .add("Unique Accession ID", "string")
  .add("Patient Date of Birth", "string")
  .add("Patient Gender", "string")
  .add("Patient State", "string")
  .add("Patient Zip Code", "string")
  .add("Diagnosis Codes", "string")
  .add("Laboratory Diagnosis", "string")
  .add("Performing Organization Name", "string")
  .add("Performing Organization Address 1", "string")
  .add("Performing Organization Address 2", "string")
  .add("Performing Organization City", "string")
  .add("Performing Organization State", "string")
  .add("Performing Organization Zip Code", "string")
  .add("Ordering Practice Name", "string")
  .add("Ordering Practice Address 1", "string")
  .add("Ordering Practice Address 2", "string")
  .add("Ordering Practice City", "string")
  .add("Ordering Practice State", "string")
  .add("Ordering Practice Zip Code", "string")
  .add("Ordering Provider NPI Number", "string")
  .add("Ordering Provider First Name", "string")
  .add("Ordering Provider Last Name", "string")
  .add("Ordering Provider Middle Initial", "string")
  .add("Ordering Provider Suffix", "string")
  .add("Test Order Code", "string")
  .add("Test Order Name", "string")
  .add("Test Specimen Receipt DateTime", "string")
  .add("Test Observation Date", "string")
  .add("Test Classification", "string")
  .add("Gene", "string")
  .add("Inheritance", "string")
  .add("cDNA", "string")
  .add("pdot", "string")
  .add("ISCN", "string")
  .add("Variant Interpretation", "string")
  .add("Zygosity", "string")
  .add("Patient Phenotypes", "string")
  .add("Test Specimen Type", "string")
  .add("InputFilename", "string")
  .add("Token_1", "string")
  .add("Token_2", "string")
  .add("Token_3", "string")
  .add("Token_4", "string")
  .add("Token_7", "string")
  .add("TokenEncryptionKey", "string")

// COMMAND ----------

// MAGIC %md
// MAGIC **Company M**

// COMMAND ----------

val schema_1758291487 =  new StructType()
  .add("patient_dob", "string")
    .add("patient_gender", "string")
    .add("ordering_provider_name", "string")
    .add("ordering_provider_institution", "string")
    .add("patient_provider_name", "string")
    .add("patient_provider_institution", "string")
    .add("diagnosis_codes", "string")
    .add("test_order_name", "string")
    .add("test_result_value", "string")
    .add("gene", "string")
    .add("coding", "string")
    .add("protein", "string")
    .add("lab_report_date", "string")
    .add("zygosity", "string")
    .add("inheritance", "string")
    .add("lab_name", "string")
    .add("token_1", "string")
    .add("token_2", "string")
    .add("token_101", "string")
    .add("token_102", "string")
    .add("token_103", "string")
    .add("token_encryption_key", "string")

// COMMAND ----------

// MAGIC %md
// MAGIC Neogenomics

// COMMAND ----------

// test result table with 18 columns
val schema_1759258658 = new StructType()
    .add("TESTORDERID", "string")
    .add("TESTCODE", "string")
    .add("TESTNAME", "string")
    .add("RESULTCODE", "string")
    .add("RESULTNAME", "string")
    .add("RESULTVALUE", "string")
    .add("RESULTUNIT", "string")
    .add("RESULTVALUE2", "string")
    .add("GENENAME", "string")
    .add("HGVSP", "string")
    .add("CONSEQUENCE", "string")
    .add("MUTANT_ALLELE_FREQ", "string")
    .add("NUCLEOTIDECHANGE", "string")
    .add("ISCN", "string")
    .add("CLASSIFICATION", "string")
    .add("FUSION_GENE_ID", "string")
    .add("FUSION_GENES", "string")
    .add("COORDINATES", "string")
    

//  test order table with 26 columns
val schema_1759258587 = new StructType()
    .add("TESTORDERID", "string")
    .add("CASENO", "string")
    .add("ACCESSIONID", "string")
    .add("PATIENTID", "string")
    .add("CLIENTID", "string")
    .add("PROVIDER_ID_ORDERING", "string")
    .add("PROVIDER_ID_TREATING", "string")
    .add("COHORT", "string")
    .add("STATUS", "string")
    .add("LEVEL_OF_SERVICE", "string")
    .add("TECHNOLOGY", "string")
    .add("CASE_TYPE_NAME", "string")
    .add("BODYSITE", "string")
    .add("SPECIMENTYPE", "string")
    .add("SPECIMENTRANSPORT", "string")
    .add("ICDCODES", "string")
    .add("SPECIMEN_COLLECTION_DATE", "string")
    .add("TEST_ORDERED_DATE", "string")
    .add("TEST_REPORTED_DATE", "string")
    .add("TEST_CANCELLED_DATE", "string")
    .add("PANELCODE", "string")
    .add("PANELNAME", "string")
    .add("TESTCODE", "string")
    .add("TESTNAME", "string")
    .add("LAB_DX", "string")
    .add("SNOMED_CODE", "string")

// provider table with 5 columns
val schema_1759258415 = new StructType()
    .add("PROVIDERID", "string")
    .add("NPI", "string")
    .add("LAST_NAME", "string")
    .add("FIRST_NAME", "string")
    .add("PROVIDER_SPECIALTY", "string")

// client table with 9 columns
val schema_1759257974 = new StructType()
    .add("CLIENTID", "string")
    .add("CLIENTNO", "string")
    .add("NAME", "string")
    .add("ADDRESS1", "string")
    .add("ADDRESS2", "string")
    .add("CITY", "string")
    .add("STATE", "string")
    .add("ZIP", "string")
    .add("COUNTRY", "string")

// patient table with 18 columns
val schema_1764140324 = new StructType()
    .add("FirstName", "string")
    .add("LastName", "string")
    .add("Gender", "string")
    .add("DateOfBirth", "string")
    .add("Zip", "string")
    .add("Address1", "string")
    .add("City", "string")
    .add("PATIENTID", "string")
    .add("token_1", "string")
    .add("token_2", "string")
    .add("token_4", "string")
    .add("token_6", "string")
    .add("token_17", "string")
    .add("token_101", "string")
    .add("token_102", "string")
    .add("token_103", "string")
    .add("token_104", "string")
    .add("token_105", "string")
    .add("token_106", "string")
    .add("token_encryption_key", "string") 



// COMMAND ----------

val schema_12345 = new StructType()
  .add("Unique Accession ID", "string")
  .add("Patient Date of Birth", "string")
  .add("Patient Gender", "string")
  .add("Patient State", "string")
  .add("Patient Zip Code", "string")
  .add("Diagnosis Codes", "string")
  .add("Laboratory Diagnosis", "string")
  .add("Performing Organization Name", "string")
  .add("Performing Organization Address 1", "string")
